# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Comcute
description:
    pl: System utrzymania wielkiej mocy obliczeniowej w sytuacjach kryzysowych
    en: System for providing big computing power in a crisis situation
baseurl: "" # the subpath of your site, e.g. /comcute
url: "http://comcute.eti.pg.gda.pl"

# Build settings
markdown: kramdown

sass:
  style: compressed

header_pages:
 - index.md
 - index-en.md
 - articles.pl.md
 - articles.en.md
 - video.pl.md
 - video.en.md
 - authors.pl.md
 - authors.en.md
 - settings.pl.md
 - settings.en.md

languages: ["pl", "en"]
default_lang: "pl"
exclude_from_localization: ["js", "images", "videos", "static", "css"]
parallel_localization: false

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - js/comcute/
   - js/spec/
   - js/Rakefile